# Video Game Research Project: Planning Stage

## 1. Data Description

In [1]:
library(tidyverse)
options(repr.matrix.max.rows = 6)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### Dataset summary  
Data generated by research group in Computer Science at UBC, led by Frank Wood.  
Game research project goal is to enable advanced AI research by analyzing player's actions on a MineCraft(PLAICraft) server.
Data collected from the people who signed up and played on PLAICraft server. 
#### Players dataset summary    
Contains a list of all unique players and data about each player.   
**Number of observations**: 196   
**Number of variables**: 7  
**Summary statistics**:
|                            |Average    |Min    |Max|
|----------------------------|-----------|-------|-------|
|**Total time played (in hours)**|5.85       |0      |223.10|
|**User's age**                 |21         |9      |58|    

**Variables**:  
- `experience`(character) - User's experience level. Five categories: Pro, Veteran, Amateur, Regular and Beginner.
- `subscribe`(logical) - User's subscription status to a game-related newsletter.
- `hashedEmail`(character) - Encoded user's email.
- `played_hours`(double) - Total hours played by user.
- `name`(character) - User's first name.
- `gender`(character) - User's gender. Seven categories: Male, Female, Non-binary, Prefer not to say, Agender, Two-Spirited, Other.
- `Age`(integer) - User's age.  
**Potential issues**:
  - inconsistent column names
  - missing age values
  - factor values stored as charcters
  - played hours precision (stored as hours not minutes)  
### Sessions dataset summary
Contains a list of individual play sessions by each player and data about the session.  
**Number of observations**: 1535   
**Number of variables**: 5  
**Observation period**: 06/04/2024 - 26/09/2024   
**Variables**:  
- `hashedEmail`(character) - Encoded user's email.
- `start_time`(character) - Formatted date and time of the player`s game session start.
- `end_time`(character) - Formatted date and time of the player`s game session end.
- `original_start_time`(double) - Date and time of the player`s game session start stored as a number.
- `original_end_time`(double) - Date and time of the player`s game session end stored as a number.  
**Potential issues**:
  - inconsistent column names
  - missing time values
  - start_time and end_time stored as character values, not in a dattime format

#### Computation of players dataset summary

In [2]:
url_players <- "https://raw.githubusercontent.com/ALagodzinska/project_planning_stage/refs/heads/main/data/players.csv"

players <- read_delim(url_players, delim = ",")
# Converted categorical variables into factors for summary
players <- players |> mutate(experience = as_factor(experience), gender = as_factor(gender))
players

summary(players)

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    experience subscribe
1   Pro         TRUE
2   Veteran     TRUE
3   Veteran    FALSE
⋮   ⋮          ⋮
194 Amateur    FALSE
195 Amateur    FALSE
196 Pro         TRUE
    hashedEmail
1   f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d
2   f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9
3   b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28
⋮   ⋮
194 d572f391d452b76ea2d7e5e53a3d38bfd7499c7399db299bd4fedb06a46ad5bb
195 f19e136ddde68f365afc860c725ccff54307dedd13968e896a9f890c40aea436
196 d9473710057f7d42f36570f0be83817a4eea614029ff90cf50d8889cdd729d11
    played_hours name      gender            Age
1   30.3         Morgan    Male               9
2    3.8         Christian Male              17
3    0.0         Blake     Male              17
⋮   ⋮            ⋮         ⋮                 ⋮
194 0.0          Dylan     Prefer not to say 57
195 2.3          Harlow    Male              17
196 0.2          Ahmed     Other             NA

    experience subscribe       hashedEmail         played_hours
 Pro     :14   Mode :logical   Length:196         Min.   :  0.000
 Veteran :48   FALSE:52        Class :character   1st Qu.:  0.000
 Amateur :63   TRUE :144       Mode  :character   Median :  0.100
 Regular :36                                      Mean   :  5.846
 Beginner:35                                      3rd Qu.:  0.600
                                                  Max.   :223.100

     name                         gender         Age
 Length:196         Male             :124   Min.   : 9.00
 Class :character   Female           : 37   1st Qu.:17.00
 Mode  :character   Non-binary       : 15   Median :19.00
                    Prefer not to say: 11   Mean   :21.14
                    Agender          :  2   3rd Qu.:22.75
                    Two-Spirited     :  6   Max.   :58.00
                    Other            :  1   NA's   :2

#### Computation of sessions dataset summary

In [3]:
url_sessions <- "https://raw.githubusercontent.com/ALagodzinska/project_planning_stage/refs/heads/main/data/sessions.csv"

sessions <- read_delim(url_sessions, delim = ",")
sessions

summary(sessions)

# Used for observation period summary
print("First record date")
data_start_date <- sessions |> slice_min(original_start_time, n = 1) |> 
    select(start_time) |> slice(1) |> pull() |> strsplit(" ")
data_start_date

print("Last record date")
data_end_date <- sessions |> slice_max(original_end_time, n = 1) |>
    select(end_time) |> slice(1) |> pull() |> strsplit(" ")
data_end_date

Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

     hashedEmail
1    bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2    36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3    f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
⋮    ⋮
1533 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1534 fd6563a4e0f6f4273580e5fedbd8dda64990447aea5a33cbb5e894a3867ca44d
1535 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
     start_time       end_time         original_start_time original_end_time
1    30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2    17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3    25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
⋮    ⋮                ⋮                ⋮                   ⋮
1533 28/07/2024 15:36 28/07/2024 15:57 1.72218e+12         1.72218e+12
1534 25/07/2024 06:15 25/07/2024 06:22 1.72189e+12         1.72189e+12
1535 20/05/2024 02:26 20/05/2024 02:45 1.71617e+12         1.71617e+12

 hashedEmail         start_time          end_time         original_start_time
 Length:1535        Length:1535        Length:1535        Min.   :1.712e+12
 Class :character   Class :character   Class :character   1st Qu.:1.716e+12
 Mode  :character   Mode  :character   Mode  :character   Median :1.719e+12
                                                          Mean   :1.719e+12
                                                          3rd Qu.:1.722e+12
                                                          Max.   :1.727e+12

 original_end_time
 Min.   :1.712e+12
 1st Qu.:1.716e+12
 Median :1.719e+12
 Mean   :1.719e+12
 3rd Qu.:1.722e+12
 Max.   :1.727e+12
 NA's   :2

[1] "First record date"

[[1]]
[1] "06/04/2024" "09:35"

[1] "Last record date"

[[1]]
[1] "26/09/2024" "07:39"

## 2. Questions

### Broad question
- **Question 3:** What time windows are most likely to have large number of simultaneous players?

### Specific question
- Can the time of the day and the day of the week predict the number of active players in the sessions dataset?

The collected start and end time session data can help to identify times when the player was present. This data can be used to calculate the number of active players within each defined period.   
To be able to answer this question, we need to extract times and days of the week from the time columns, add new columns for these new values. Then group data by date, time period and the day of the week and add the column that will summarize the number of active players. Time period and day of the week might be be categorical values.